### ISSUE TITLE
RichEmbed is not a constructor

### ISSUE THREAD

**Issue by ghost** [The-SourceCode/Open-SourceBot#75]
RichEmbed is not a constructor

`TypeError: RichEmbed is not a constructor
    at module.exports.run (/home/pixel/Desktop/Fl4nnelBot/modules/general/commands/help.js:93:19)
    at Client.client.on (/home/pixel/Desktop/Fl4nnelBot/handler/Handler.js:209:19)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/pixel/Desktop/Fl4nnelBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/pixel/Desktop/Fl4nnelBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/pixel/Desktop/Fl4nnelBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/pixel/Desktop/Fl4nnelBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/pixel/Desktop/Fl4nnelBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/pixel/Desktop/Fl4nnelBot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
`

![Screenshot at 2020-07-15 15-46-03](https://user-images.githubusercontent.com/60579010/87601430-77df3900-c6cb-11ea-97eb-025647701d72.png)

**Comment by abdullahpear** [comment]
RichEmbed is deprecated in discord.js v12, to replace that use MessageEmbed instead.

**Comment by abdullahpear** [comment]
and node can't find your file called config.json, either it doesn't exist, or wrong path.

**Comment by ghost** [comment]
actually im using nodemon, so the first error was fixed!

**Comment by ghost** [comment]
but now it is giving me this
`[nodemon] starting `node index.js`
Logged in as Fl4nnelBot#9981
(node:17069) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:443:8)
    at MessageEmbed.setup (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:77:91)
    at new MessageEmbed (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/APIMessage.js:164:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/APIMessage.js:164:31)
    at TextChannel.send (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at module.exports.run (/home/pixel/Desktop/to back up/Fl4nnelBot/modules/general/commands/help.js:99:21)
    at Client.client.on (/home/pixel/Desktop/to back up/Fl4nnelBot/handler/Handler.js:209:19)
    at Client.emit (events.js:198:13)
(node:17069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by alhassanv** [comment]
> but now it is giving me this
> `[nodemon] starting `node index.js` Logged in as Fl4nnelBot#9981 (node:17069) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function at Function.normalizeFields (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:443:8) at MessageEmbed.setup (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:77:91) at new MessageEmbed (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/MessageEmbed.js:18:10) at embedLikes.map.e (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/APIMessage.js:164:40) at Array.map (<anonymous>) at APIMessage.resolveData (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/APIMessage.js:164:31) at TextChannel.send (/home/pixel/Desktop/to back up/Fl4nnelBot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62) at module.exports.run (/home/pixel/Desktop/to back up/Fl4nnelBot/modules/general/commands/help.js:99:21) at Client.client.on (/home/pixel/Desktop/to back up/Fl4nnelBot/handler/Handler.js:209:19) at Client.emit (events.js:198:13) (node:17069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:17069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Update nodejs version to atleast v12

**Comment by ghost** [comment]
fuck, i didnt noticed, the apt repository for nodejs in ubuntu is stuck on v10, lmao
